import Head from 'next/head'
import { createClient, MicroCMSDate, MicroCMSImage } from 'microcms-js-sdk'
import { GetStaticProps, NextPage } from 'next'
import Picture from '../components/MicroCMSPicture'

type MicroCMSApiImage = {
  default_image: MicroCMSImage
  art_directive_image: {
    fieldId: 'art_directive_image'
    default_image: MicroCMSImage
    md_image: MicroCMSImage
    lg_image: MicroCMSImage
    '2xl_image': MicroCMSImage
  }
}

type Props = MicroCMSApiImage & MicroCMSDate

export const getStaticProps: GetStaticProps<Props> = async () => {
  const content = await createClient({
    serviceDomain: process.env.MICROCMS_SERVICE_DOMAIN,
    apiKey: process.env.MICROCMS_API_KEY,
  }).getObject<MicroCMSApiImage>({ endpoint: 'image' })

  return {
    props: {
      ...content,
    },
  }
}

const Home: NextPage<Props> = ({ default_image }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>通常の画像</h2>
        <Picture
          src={default_image.url}
          width={default_image.width}
          height={default_image.height}
          alt=""
        />

        <h2>アートディレクション画像</h2>
      </main>
    </div>
  )
}

export default Home
